services:
  backend:
    build: .
    container_name: django_app
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      - main
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always  
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
    depends_on:
      - backend
    networks:
      - main
    restart: always

volumes:
  postgres_data:

networks:
  main:
